defaultPlacement: end
fieldLayouts:
  0eba97bf-493e-4c8e-9f8b-aa715e370e74:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  d02fb476-fe13-4a5d-b8c7-ef3d23e942c6: # craftsite
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog/category/{slug}'
structure:
  maxLevels: 1
  uid: 52543bfc-ab4a-45db-b1c5-ca911e8cebe5
