columnSuffix: null
contentColumnType: string
fieldGroup: 14285a31-6834-437a-ac78-707800628d44 # Blog Post Fields
handle: postContent
instructions: ''
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
