fieldLayouts:
  ae2f5eb5-4137-493b-9cd6-8af8e2eb9797:
    tabs:
      -
        elements:
          -
            fieldUid: c2688eac-49fc-4462-882e-6d362c6d6031 # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: description
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
