defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  d02fb476-fe13-4a5d-b8c7-ef3d23e942c6: # craftsite
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
